[tool.poetry]
name = "pdf2odt"
version = "1.0.0"
description = "Converts a pdf into a Libreoffice Writer document, with images resized to A4 and anchored as character"
authors = ["turulomio <turulomio@yahoo.es>"]
license = "GPL-3.0 license"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.14,<4"
colorama = ">=0.4.6"
tqdm = ">=4.70.1"
unogenerator = ">=1.5.0"
pymupdf = "^1.28.2"
rapidocr-onnxruntime = "<=1.3.8"


[tool.poetry.group.dev.dependencies]
coverage = ">=7.16.1"
pytest = ">=9.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.scripts]
pdf2odt='pdf2odt.core:main'

[tool.poe.tasks]
test = { script = "pdf2odt.poethepoet:test" }
coverage = { script = "pdf2odt.poethepoet:coverage" }
release = { script = "pdf2odt.poethepoet:release" }
translate = { script = "pdf2odt.poethepoet:translate" }
